version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bloggers-db
    restart: always
    ports:
      - "3334:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-bloggers-dev
    networks:
      - app-network

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB_URL=postgresql://postgres:postgres@db:5432/postgres-bloggers-dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
